spring.application.name=flowforge

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/flowforge
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true